import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/navbar/NavBar";
import BurgerMenu from "@/components/burgerMenu/BurgerMenu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <div className="wrapper">
            <NavBar />
            <BurgerMenu />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
